config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories
  resources :adverts
  resources :check_lists
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :category

  has_one :check_list, dependent: :destroy

  validates :url, uniqueness: {case_sensitive: false}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :adverts, dependent: :destroy
  validates :model, :brand, presence: true, length: { minimum: 3 }
  validates :model, uniqueness: true

  def brand_model
    "#{brand} #{model}"
  end
end

app/models/check_list.rb
class CheckList < ApplicationRecord
  belongs_to :advert
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  def index
    @advert = Advert.all
  end

  def new
    @categories = Category.all
    @advert = Advert.new
    @check_list = CheckList.new
  end

  def create
    @categories = Category.all
    @advert = Advert.new(advert_params)
    @advert.check_list = CheckList.new
    if @advert.save
      redirect_to adverts_path(@advert)
    else
      render new_advert_path
    end
  end

  def show
    @advert = Advert.find(params[:id])
    @check_list = @advert.check_list
  end

  def edit
    @advert = Advert.find(params[:id])
    @categories = Category.all
    @check_list = @advert.check_list
  end

  def update
    if @advert = Advert.update(advert_params)
      redirect_to adverts_path
    else
      render edit_advert_path
    end
  end

  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    redirect_to adverts_path
  end

    private
      def advert_params
        params.require(:advert).permit(:category_id, :year, :seller, :phone, :url, :price, :vin, :city, :notes, :complectation, :category_id, :owners)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    if @category = Category.create!(category_params)
      redirect_to categories_path(@category)
    else
      render 'categories/new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    if @category = Category.update(category_params)
      redirect_to categories_path
    else
      render edit_category_path
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

    def category_params
      params.require(:category).permit(:brand, :model)
    end
end

app/controllers/check_lists_controller.rb
class CheckListsController < ApplicationController

  def index
    @check_lists = CheckList.all
  end

  def new
    @check_list = CheckList.new
  end

  def create
    @check_list = Check_list.create(check_list_params)
    redirect_to adverts_path(@advert)
  end

  def show
    @check_list = CheckList.find(params[:id])
  end

  def edit
    @check_list = CheckList.find(params[:id])
  end

  def update
    @check_list = CheckList.find(params[:id])
    @check_list.update(check_list_params)
  end

  def destroy
    @check_list = CheckList.find(params[:id])
    @check_list.destroy

    redirect_to check_list_url(@check_list)
  end

    private
      def check_list_params
        params.require(:check_list).permit(:id, :category_id, :spending, :condicion, :service, :painted, :body_repair, :price, :notes )
      end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/views/adverts/edit.html.erb
<div class="wrapper-page">
  <h1>Редактирование объявления</h1>
  <%= render 'adverts/form/form' %>
  <%= render 'check_lists/form' %>
</div>

app/views/adverts/form/_form.html.erb
<div class="input-advetrts-table table">
  <div class="advert-error-msg">
    <% if @advert.errors.any? %>
      <h2>При сохранении объявления возникли следующие проблемы:</h2>
      <ul>
        <% @advert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <%= form_for @advert do |f| %>
    <table class="table-edit">
      <tr>
        <td> <%= f.label :"Марка" %> </td>
        <td> <%= f.select :category_id, @categories.map{ |c| [c.brand_model, c.id] } %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Год выпуска:' %> </td>
        <td> <%= f.text_field :year %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Стоимость:' %> </td>
        <td> <%= f.text_field :price %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Комплектация:' %> </td>
        <td> <%= f.text_field :complectation %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Владельцы:' %> </td>
        <td> <%= f.text_field :owners %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Город:' %> </td>
        <td> <%= f.text_field :city %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Телефон:' %> </td>
        <td> <%= f.text_field :phone %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Ссылка:' %> </td>
        <td> <%= f.text_field :url %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Продавец:' %> </td>
        <td> <%= f.text_field :seller %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'VIN:' %> </td>
        <td> <%= f.text_field :vin %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Примечания:' %> </td>
        <td> <%= f.text_area :notes %> </td>
      </tr>
      <tr>
        <td class="table-cell-center" colspan="2">
          <%= f.submit 'Сохранить', :class => 'button-save-edit' %>
  <% end %>
          <%= button_to 'Назад', adverts_path, :method => :get %>
        </td>
      </tr>
    </table>
</div>

app/views/adverts/form/_index.html.erb
<div class="list-all-adverts">
  <table class="basic-table" id="adverds">
    <thead>
    <th>Марка</th>
    <th>Модель</th>
    <th>Год выпуска</th>
    <th>Стоимость</th>
    <th>Комплектация</th>
    <th>Владельцы</th>
    <th>Город</th>
    <th>Телефон</th>
    <th>Ссылка</th>
    <th>Продавец</th>
    <th>VIN</th>
    <th>Примечания</th>
    <th>Дата создания</th>
    <th>Дата редоктирования</th>
    <th colspan="2">Действия</th>
    </thead>
    <% @advert.each do |advert| %>
      <tr>
        <td> <%= link_to advert.category.brand, (advert) %></td>
        <td> <%= link_to advert.category.model, (advert) %> </td>
        <td> <%= link_to advert.year, (advert) %> </td>
        <td> <%= link_to advert.price, (advert) %> </td>
        <td> <%= link_to advert.complectation, (advert) %> </td>
        <td> <%= link_to advert.owners, (advert) %> </td>
        <td> <%= link_to advert.city, (advert) %> </td>
        <td> <%= link_to advert.phone, (advert) %> </td>
        <td>
        <form action="<%=advert.url%>">
          <button type="submit">Link</button>
        </form>
        </td>
        <td> <%= link_to advert.seller, (advert) %> </td>
        <td> <%= link_to advert.vin %>, (advert) </td>
        <td> <%= link_to advert.notes, (advert) %> </td>
        <td> <%= link_to advert.created_at.strftime("%m %d %Y"), (advert) %> </td>
        <td> <%= link_to advert.updated_at.strftime("%m %d %Y"), (advert) %> </td>
        <td> <%= button_to 'Edit', edit_advert_path(advert), :method => :get, :class => 'button button-edit' %> </td>
        <td> <%= button_to 'Delete', advert_path(advert), method: :delete, data: {confirm: 'Вы уверены?'}, :class => 'button button-delete' %> </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/adverts/form/_shoow.html.erb
<div class="show-adverts">
  <table class="basic-table">
    <thead>
    <th>Марка</th>
    <th>Модель</th>
    <th>Год выпуска</th>
    <th>Стоимость</th>
    <th>Комплектация</th>
    <th>Владельцы</th>
    <th>Город</th>
    <th>Телефон</th>
    <th>Ссылка</th>
    <th>Продавец</th>
    <th>VIN</th>
    <th>Примечания</th>
    <th>Дата создания</th>
    <th>Дата редоктирования</th>
    </thead>
    <tr>
      <td> <%= @advert.category.brand %></td>
      <td> <%= @advert.category.model %> </td>
      <td> <%= @advert.year %> </td>
      <td> <%= @advert.price %> </td>
      <td> <%= @advert.complectation %> </td>
      <td> <%= @advert.owners %> </td>
      <td> <%= @advert.city %> </td>
      <td> <%= @advert.phone %> </td>
      <td>
        <%= button_to 'Link', @advert.url, :class => 'button button-link' %>
      </td>
      <td> <%= @advert.seller %> </td>
      <td> <%= @advert.vin %> </td>
      <td> <%= @advert.notes %> </td>
      <td> <%= @advert.created_at.strftime("%m %d %Y") %> </td>
      <td> <%= @advert.updated_at.strftime("%m %d %Y") %> </td>
    </tr>
  </table>
</div>

app/views/adverts/index.html.erb
<div class="wrap">
  <h1>Все объявления</h1>
  <%= render 'layouts/nav-menu' %>
  <%= button_to 'Создать объявление', new_advert_url, :method => :get, :class => 'button-link-create' %>
  <%= render 'adverts/form/index' %>
</div>

app/views/adverts/new.html.erb
<div class="wrap">
  <h1>Новое объявление</h1>
  <%= render 'adverts/form/form' %>
</div>

app/views/adverts/show.html.erb
<div class="wrap">
  <h1>Объявление <%= @advert.category_id %></h1>
  <%= button_to 'Назад', adverts_path, :method => :get %>
  <%= render 'adverts/form/shoow' %>
  <%= render 'check_lists/form' %>
</div>

app/views/categories/edit.html.erb
<div class="wrap">
  <h1>Редактирование категории</h1>

  <%= render 'categories/form/form' %>

</div>

app/views/categories/form/_form.html.erb
<div class="input-categories-table form">
  <%= form_for @category do |f| %>
    <table class="input-table-category">
      <tr>
      <td> <%= f.label :'Производитель:' %></td><td><%= f.text_field :brand %> </td>
      </tr>
      <tr>
      <td> <%= f.label :'Модель:' %> </td><td> <%= f.text_field :model %> </td>
      </tr>
      <tr>
      <td class="table-cell-center" colspan="2">
        <%= f.submit 'Сохранить', :class => 'button-save-edit' %>
      </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/categories/form/_new.html.erb
<div class="input-categories-table form">
  <%= form_for Category.new do |f| %>
    <table class="input-table-category">
      <td> <%= f.label :'Производитель:' %></td><td><%= f.text_field :brand %> </td>
      <td> <%= f.label :'Модель:' %> </td><td> <%= f.text_field :model %> </td>
      <td class="table-cell-center" colspan="2">
        <%= f.submit 'Сохранить', :class => 'button-save-edit' %>
      </td>
    </table>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="wrap">
  <h1>Все категории</h1>
  <%= render 'layouts/nav-menu' %>
  <%= render 'categories/form/new' %>
  <table class="basic-table" id="categories">
    <thead>
      <th>Производитель</th>
      <th>Модель</th>
    </thead>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.brand, (category) %></td>
        <td><%= link_to category.model, (category) %></td>
        <td><%= button_to 'Редактировать', edit_category_path(category), :method => :get, :class => 'button button-edit' %></td>
        <td><%= button_to 'Удалить', category_path(category), :method => :delete, data: {confirm: "Вы уверены?"}, :class => 'button button-delete' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/categories/new.html.erb
<div class="wrap">
  <h1>Создание категории</h1>

  <%= render 'categories/form/form' %>

</div>

app/views/categories/show.html.erb
<div class="wrap">
  <h1>Категория <%= @category.brand %></h1>

  <table class="basic-table">
    <tr>
      <td> Производитель: </td>
      <td> <%= @category.brand %> </td>
    </tr>
    <tr>
      <td> Модель: </td>
      <td> <%= @category.model %> </td>
    </tr>
    <tr>
      <td colspan="2" class="table-cell-center">
        <%= button_to 'Редактировать', edit_category_url(@category), :method => :get, :class => 'button-edit' %>
        <%= button_to 'Удалить', category_url(@category), method: :delete, data: {confirm: 'Вы уверены?'}, :class => 'button-delete' %>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="table-cell-center">
        <%= button_to 'Назад', categories_url(@category), :method => :get, :class => 'button-back' %>
      </td>
    </tr>
  </table>
</div>

app/views/check_lists/_check-list.html.erb
<div class="check-list">
  <table class="basic-table">
    <tr>
      <td colspan="2" class="row-table-title">
        Чек лист
      </td>
    </tr>
    <tr>
      <td> Вложения: </td>
      <td> <%= @check_list.spending %> </td>
    </tr>
    <tr>
      <td> Состояние: </td>
      <td> <%= @check_list.condicion %> </td>
    </tr>
    <tr>
      <td> Обслуживание: </td>
      <td> <%= @check_list.service %> </td>
    </tr>
    <tr>
      <td> Красилась ли: </td>
      <td> <%= @check_list.painted %> </td>
    </tr>
    <tr>
      <td> Кузовной ремонт: </td>
      <td> <%= @check_list.body_repair %> </td>
    </tr>
    <tr>
      <td> Стоимость </td>
      <td> <%= @check_list.price %> </td>
    </tr>
    <tr>
      <td> Примечания: </td>
      <td> <%= @check_list.notes %> </td>
    </tr>
  </table>
</div>

app/views/check_lists/_form.html.erb
<div class="new-check-list">
  <h2>Чек лист</h2>
  <%= form_for @check_list do |f| %>
    <table class="basic-table table-new">
      <tr>
        <td> <%= f.label :'Вложения:' %> </td>
        <td> <%= f.select(:spending, ['Не требует', 'Незначительные', 'Средне','Большие'], {include_blank: 'Выбери пункт'}) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Состояниe:' %> </td>
        <td> <%= f.select(:condicion, ['Отличное','Хорошее', 'Среднее', 'Плохое', "Ведро с гайками"], {include_blank: 'Выбери пункт'}) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Обслуживание:' %> </td>
        <td> <%= f.select(:service, ['Есть сервисная книжка', 'Регулярное', 'Периодическое', 'Эпизодическео'] ) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Красился ли А/М:' %> </td>
        <td> <%= f.select(:painted, ['Не крашен', 'Кузовные элементы', 'Кузом целиком']) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Кузовной ремонт:' %> </td>
        <td> <%= f.select(:body_repair, ['Не ремонтировался', 'Вытягивались элементы', 'Менялись элементы', 'Вытягивался силовой каркас']) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Стоимость:' %> </td>
        <td> <%= f.text_field :price %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Примечания:' %> </td>
        <td> <%= f.text_area :notes %> </td>
      </tr>
      <tr>
        <td class='table-cell-center' colspan="2">
          <%= f.submit 'Сохранить', :class => 'button-create' %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/check_lists/edit.html.erb
<div class="wrap">
  <h1>Редактирование чек листа</h1>
  <%= form_for @check_list do |f| %>
    <table class="basic-table table-edit">
      <tr>
        <td> <%= f.label :'Вложения:' %> </td>
        <td> <%= f.select(:spending, ['Не требует', 'Незначительные', 'Средне','Большие'], {include_blank: 'Выбери пункт'}) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Состояниe:' %> </td>
        <td> <%= f.select(:condicion, ['Отличное','Хорошее', 'Среднее', 'Плохое', "Ведро с гайками"], {include_blank: 'Выбери пункт'}) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Обслуживание:' %> </td>
        <td> <%= f.select(:service, ['Есть сервисная книжка', 'Регулярное', 'Периодическое', 'Эпизодическео'] ) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Красился ли А/М:' %> </td>
        <td> <%= f.select(:painted, ['Не крашен', 'Кузовные элементы', 'Кузом целиком']) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Кузовной ремонт:' %> </td>
        <td> <%= f.select(:body_repair, ['Не ремонтировался', 'Вытягивались элементы', 'Менялись элементы', 'Вытягивался силовой каркас']) %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Стоимость:' %> </td>
        <td> <%= f.text_field :price %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Примечания:' %> </td>
        <td> <%= f.text_area :notes %> </td>
      </tr>
      <tr>
        <td class='table-cell-center' colspan="2">
          <%= f.submit 'Сохранить изменения', :class => 'button-save-edit' %>
        </td>
      </tr>
      <tr>
  <% end %>
  <td class='table-cell-center' colspan="2">
    <%= button_to 'Назад', check_lists_url, :method => :get, :class => 'button-back' %>
  </td>
  </tr>
    </table>
</div>

app/views/check_lists/index.html.erb
<div class="wrap">
  <h1>Все чек листы</h1>
  <%= render 'layouts/nav-menu' %>
  <table class="basic-table">
    <thead>
      <th>Вложения</th>
      <th>Состояние</th>
      <th>Обслуживание</th>
      <th>Красился ли А/М</th>
      <th>Кузовной ремонт</th>
      <th>Стоимость</th>
      <th>Примечания</th>
      <th>Дата создания</th>
      <th>Дата редактирования</th>
    </thead>
    <% @check_lists.each do |check_list| %>
      <tr>
        <td> <%= link_to check_list.spending, (check_list) %> </td>
        <td> <%= link_to check_list.condicion, (check_list) %> </td>
        <td> <%= link_to check_list.service, (check_list) %> </td>
        <td> <%= link_to check_list.painted, (check_list) %> </td>
        <td> <%= link_to check_list.body_repair, (check_list) %> </td>
        <td> <%= link_to check_list.price, (check_list) %> </td>
        <td> <%= link_to check_list.notes, (check_list) %> </td>
        <td> <%= button_to 'Редактировать', edit_check_list_url(check_list), :method => :get, :class => 'button button-edit' %> </td>
        <td> <%= button_to 'Удалить', check_list_url(check_list), method: :delete, data: {confirm: 'Вы уверены?'}, :class => 'button button-delete' %> </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/check_lists/new.html.erb
<div class="wrap">
  <h1>Новый чек лист</h1>

  <%= form_for @check_list do |f| %>
    <table class="table-new">
      <tr>
        <td> <%= f.label :'Вложения:' %> </td>
        <td> <%= f.text_field :spending %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Состояниe:' %> </td>
        <td> <%= f.text_field :condicion %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Обслуживание:' %> </td>
        <td> <%= f.text_field :service %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Красился ли А/М:' %> </td>
        <td> <%= f.text_field :painted %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Кузовной ремонт:' %> </td>
        <td> <%= f.text_field :body_repair %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Стоимость:' %> </td>
        <td> <%= f.text_field :price %> </td>
      </tr>
      <tr>
        <td> <%= f.label :'Примечания:' %> </td>
        <td> <%= f.text_area :notes %> </td>
      </tr>
      <tr>
        <td class='table-cell-center' colspan="2">
          <%= f.submit 'Создать чек-лист', :class => 'button-create' %>
        </td>
      </tr>
      <tr>
  <% end %>
        <td class='table-cell-center' colspan="2">
          <%= button_to 'Назад', check_lists_url, :method => :get, :class => 'button-back' %>
        </td>
      </tr>
    </table>
</div>

app/views/check_lists/show.html.erb
<div class="wrap">
  <h1>Просмотр чек листа</h1>
  <%=render 'check_lists/check-list' %>
<!--  <table class="basic-table">-->
<!--    <tr>-->
<!--      <td> Вложения: </td>-->
<!--      <td> <%#= @check_list.spending %> </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td> Состояние: </td>-->
<!--      <td> <%#= @check_list.condicion %> </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td> Обслуживание: </td>-->
<!--      <td> <%#= @check_list.service %> </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td> Красилась ли: </td>-->
<!--      <td> <%#= @check_list.painted %> </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td> Кузовной ремонт: </td>-->
<!--      <td> <%#= @check_list.body_repair %> </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td> Стоимость </td>-->
<!--      <td> <%#= @check_list.price %> </td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td> Примечания: </td>-->
<!--      <td> <%#= @check_list.notes %> </td>-->
<!--    </tr>-->
<!--  </table>-->
</div>

app/views/layouts/_nav-menu.html.erb
<div class="nav-menu">
  <table>
<!--    <tr><%#= link_to 'Объявления', adverts_path %></tr>-->
    <tr><%= button_to 'Объявления', adverts_path, :method => :get %></tr>
    <tr><%= button_to 'Категории', categories_path, :method => :get %></tr>
    <tr><%= button_to 'Чек листы', check_lists_path, :method => :get %></tr>
  </table>
</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Project Perekup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>